sudo: required
dist: xenial

language: go
go:
  - 1.11

services: docker

script:
  - cd OSSMediatorCollector && make all && cd ..
  - cd ElasticsearchPlugin && make all && cd ..

after_script:
  - 'echo "OSSMediatorCollector test results:" && cat OSSMediatorCollector/OSSMediatorCollector-unittest-result.txt'
  - 'echo "ElasticsearchPlugin test results:" && cat ElasticsearchPlugin/elasticsearchplugin-unittest-result.txt'
  - 'grep -e "FAIL:" OSSMediatorCollector/OSSMediatorCollector-unittest-result.txt && { echo "OSSMediatorCollector unit tests failed"; exit 1; }'
  - 'grep -e "FAIL:" ElasticsearchPlugin/elasticsearchplugin-unittest-result.txt && { echo "ElasticsearchPlugin unit tests failed"; exit 1; }'

after_failure:
  - '[ -s mediator_lint_result.txt ] && echo "Lint Errors:" && cat mediator_lint_result.txt'
